model: [GIN]
epochs: [350]
max_struct_size: [0]
folds: [10]
cliques: [0]
rings: [0]
aggr_edge_atr: [0]
aggr_vertex_feat: [0]
explicit_pattern_enc: [0]
edge_attr_in_vertices: [0]
clean: [1]
batch_size: [128, 64, 32, 16]
lr: [0.01, 0.001, 0.0001, 0.0005, 0.00001]
drop_out: [0, 0.5]
num_layers: [2,3,5]
lr_scheduler_decay_steps: [50,200]
lr_scheduler_decay_rate: [0.5,0.9,0.99]
emb_dim: [32, 64, 128, 256]
